# Dockerfile.dev

FROM node:20

# 워킹 디렉토리 지정
WORKDIR /app

# 의존성 설치
COPY package*.json ./
RUN npm install

# 소스 복사
COPY . .

# 개발 서버용 환경변수 세팅은 따로 .env.dev에서 처리

# dev 환경은 핫리로드용 도구 설치 필요 (npm i -D @nestjs/cli ts-node-dev)
RUN npm install -g @nestjs/cli

# expose는 Nest 기본 포트 3000
EXPOSE 3000

# 핫리로드 실행
CMD ["npm", "run", "start:dev"]
