# .github/workflows/deploy-dev.yml

name: Deploy to EC2 (Development)

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    name: Deploy Dev EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEV_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Generate .env
        run: |
          echo "NODE_ENV=development" > .env
          echo "DB_HOST=${{ secrets.DEV_DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DEV_DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=${{ secrets.DEV_DB_DATABASE }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Upload .env to EC2
        run: |
          scp -o StrictHostKeyChecking=no .env ec2-user@${{ secrets.DEV_EC2_HOST }}:/home/ec2-user/dagledagle/.env

      - name: Deploy via SSH
        run: |
          ssh ec2-user@${{ secrets.DEV_EC2_HOST }} '
            set -e

            # Git 설치
            if ! command -v git &> /dev/null; then
              sudo yum install -y git
            fi

            # 프로젝트 clone
            if [ ! -d dagledagle ]; then
              git clone git@github.com:ghrltjdtprbs/dagledagle.git
            fi

            cd dagledagle
            git fetch origin
            git checkout -B develop origin/develop

            # Docker 배포
            docker-compose -f docker-compose.dev.yml down || true
            docker-compose -f docker-compose.dev.yml up -d --build
          '
